### PR TITLE
return errors when a negative value is returned from Pm_Read

### PR DESCRIPTION
**Pull request by kisielk**

### CODE REVIEW

**Comment by kisielk** [comment]
I also recommend merging #17. The values in errorMap are incorrect, eg: 1 should be -9999, 2 should be -9998, etc. But #17 will eliminate the need for errorMap entirely.

**Comment by rakyll** [comment]
Left comments to #17, I agree that it should be merged.

@kisielk, have you signed a Google CLA before? I cannot accept the PR without [Google's CLA](https://cla.developers.google.com/about/google-individual?csw=1) since the code is licensed to Google.

**Comment by kisielk** [comment]
Yep, I'm in the Go contributors list.

**Comment by rakyll** [comment]
Oh, ok. Merging. Thanks!

**Pull request merged**
